name: Rust

on:
  push:
    branches: ["main"]
    tags: # This triggers the workflow on any tag push as well
      - "v*" # Only push tags starting with "v" (e.g., v1.0.0)

  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Build the project
      - name: Build
        run: cargo build --verbose

      # Run tests
      - name: Run tests
        run: cargo test --verbose

      # Automatically create a GitHub release when a tag is pushed
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}

      # Optionally, upload built artifacts to the release
      - name: Upload Release Assets
        if: startsWith(github.ref, 'refs/tags/') # Runs only on tag pushes
        uses: actions/upload-artifact@v3
        with:
          name: executable
          path: target/release/aprinter # Path to your executable or assets to upload
